#!/bin/bash

export NVM_DIR="$HOME/.nvm"
GIT_ROOT="$(git rev-parse --show-toplevel)"

# Check node version when using nvm:
[ "$(node --version)" == cat "$GIT_ROOT/.nvmrc" ] || {
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm use
}